const performanceList: any = [
  {
    category: "공동주택",
    name: "동대구역 센텀 화성파크드림",
    address: "대구광역시 동구 신암동 139-69번지 일원",
    units: "총 1,458세대",
    scale: "지하 3층 ~ 지상 15층, 22개동",
    year: "2023년 12월 ~ 진행중",
    contractor: "에이치에스화성 주식회사",
    residential: true,
  },
  {
    category: "공동주택",
    name: "디오르나인 안양역",
    address: "경기도 안양시 만안구 안양동 627-1,2,3번지",
    units: "540세대",
    scale: "지하 6층 ~ 지상 25층, 2개동",
    year: "2023년",
    contractor: "안강건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "의정부역 파밀리에",
    address: "경기도 의정부시 의정부동 127-4번지 일원",
    units: "82세대",
    scale: "지하 5층 ~ 지상 24층",
    year: "2022년",
    contractor: "신동아건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "화성파크드림 공주 월송",
    address: "충청남도 공주시 월송동 669",
    units: "303세대",
    scale: "지하 1층 ~ 지상 20층, 4개동",
    year: "2022년",
    contractor: "HXD화성개발",
    residential: true,
  },
  {
    category: "공동주택",
    name: "영종국제도시 화성파크드림 2차",
    address: "인천 경제자유구역 영종지구 영종하늘도시 A58BL",
    units: "499세대",
    scale: "지하 1층 ~ 지상 21층, 8개동",
    year: "2020년",
    contractor: "HXD화성개발",
    residential: true,
  },
  {
    category: "공동주택",
    name: "검단파라곤 보타닉파크",
    address: "인천광역시 서구 검단지구 AA14BL",
    units: "887세대",
    scale: "지하 2층 ~ 지상 25층, 10개동",
    year: "2019년",
    contractor: "동양건설산업",
    residential: true,
  },
  {
    category: "공동주택",
    name: "신동백 두산 위브 더 제니스",
    address: "경기도 용인시기흥구 동백동 419-1번지 일원",
    units: "1,187세대",
    scale: "지하 3층 ~ 지상 20~32층, 10개동",
    year: "2018년",
    contractor: "두산건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "힐스테이트 지제역",
    address: "경기도 평택 영신지구 1BL",
    units: "1,519세대",
    scale: "지하 5층 ~ 지상 22층, 16개동",
    year: "2018년",
    contractor: "현대엔지니어링",
    residential: true,
  },
  {
    category: "공동주택",
    name: "아산배방 우방 아이유쉘",
    address: "충청남도 아산시 배방읍 공수리 526일원",
    units: "1,267세대",
    scale: "지하 4층 ~ 지상 27층, 15개동",
    year: "2018년",
    contractor: "SM㈜ 우방",
    residential: true,
  },
  {
    category: "공동주택",
    name: "아산배방 2차 우방 아이유쉘",
    address: "충청남도 아산시 배방읍 공수리 193-5일원",
    units: "519세대",
    scale: "지하 4층 ~ 지상 26층, 7개동",
    year: "2018년",
    contractor: "SM상선㈜",
    residential: true,
  },
  {
    category: "공동주택",
    name: "원주기업도시 EG The1 2차",
    address: "강원도 원주시 지정면 가곡리 원주기업도시 2-1BL",
    units: "776세대",
    scale: "지하 2층 ~ 지상 29층, 7개동",
    year: "2018년",
    contractor: "라인건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "인천 청라 푸르지오",
    address: "인천광역시 청라지구 A-8BL",
    units: "751세대",
    scale: "지하 1층 ~ 지상 58층, 4개동",
    year: "2017년",
    contractor: "대우건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "오산 센트럴 푸르지오",
    address: "경기도 오산시 오산동 11-1번지 일원",
    units: "920세대",
    scale: "지하 2층 ~ 지상 25층, 10개동",
    year: "2016년",
    contractor: "대우건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "평택 효성 해링턴 플레이스",
    address: "경기도 평택시 소사동",
    units: "1BL : 710세대 / 2BL : 2,530세대 (총 3,240세대)",
    scale: "지하 2층 ~ 지상 30층, 40개동",
    year: "2016년",
    contractor: "㈜ 효성",
    residential: true,
  },
  {
    category: "공동주택",
    name: "수지 성복 아이비힐",
    address: "경기도 용인시 성복동 539번지 일원",
    units: "66세대",
    scale: "지하 1층 ~ 지상 4층, 12개동",
    year: "2016년",
    contractor: "㈜ 한양산업개발, ㈜코람코자산신탁",
    residential: true,
  },
  {
    category: "공동주택",
    name: "동탄2신도시 3차 푸르지오",
    address: "경기도 화성시 영천동 11번지 일원",
    units: "913세대",
    scale: "지하 2층 ~ 지상 20층, 10개동",
    year: "2016년",
    contractor: "대우건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "김천혁신도시 EG The1",
    address: "경상북도 김천혁신도시 3-1, Ac1BL",
    units: "486세대",
    scale: "지하 1층 ~ 지상 19~25층, 6개동",
    year: "2016년",
    contractor: "㈜라인건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "천안 레이크타운 2차 푸르지오",
    address: "천안시 서북구 성성동 130-4번지 일원",
    units: "1,730세대",
    scale: "지하 2층 ~ 지상 39층, 13개동",
    year: "2015년",
    contractor: "대우건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "길음역 동양 파라곤",
    address: "서울특별시 성북구 돈암동 624번지 일원",
    units: "525세대",
    scale: "지하 5층 ~ 지상 30층, 7개동",
    year: "2015년",
    contractor: "동양건설산업",
    residential: true,
  },
  {
    category: "공동주택",
    name: "부천 아이파크",
    address: "경기도 부천시 원미구 약대동 181번지 일원",
    units: "1,613세대",
    scale: "지하 2층 ~ 지상 25층, 23개동",
    year: "2014년",
    contractor: "HDC현대산업개발",
    residential: true,
  },
  {
    category: "공동주택",
    name: "아산 테크노밸리 EG The1 1차",
    address: "충청남도 아산 테크노밸리 Ab-6, Ac-1BL",
    units: "1,013세대",
    scale: "지하 1층 ~ 지상 25층, 7개동",
    year: "2013년",
    contractor: "㈜EG건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "동탄2기 신도시 EG The1",
    address: "경기도 화성시 동탄면 영천동 산27-37",
    units: "642세대",
    scale: "지하 2층 ~ 지상 15층, 12개동",
    year: "2013년",
    contractor: "㈜EG건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "동탄 롯데캐슬 알바트로스",
    address: "경기도 화성시 동탄순환대로21길 53",
    units: "1,416세대",
    scale: "지하 1층 ~ 지상 29층, 16개동",
    year: "2013년",
    contractor: "롯데건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "한강 신도시 롯데캐슬",
    address: "경기도 김포시 김포한강11로 275",
    units: "1,136세대",
    scale: "지하 5층 ~ 지상 29층, 14개동",
    year: "2013년",
    contractor: "롯데건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "의정부 우미쁘띠린 1,2차",
    address: "경기도 의정부시 의정부동 166-12",
    units: "297세대",
    scale: "지하 5층 ~ 지상 25층, 2개동",
    year: "2011년",
    contractor: "우미건설",
    residential: true,
  },
  {
    category: "공동주택",
    name: "일산 식사자이",
    address: "경기도 일산동구 식사도시개발구역 1,2,4BL",
    units: "4,683세대",
    scale: "지하 2층 ~ 지상 30층, 41개동",
    year: "2011년",
    contractor: "GS건설",
    residential: true,
  },
  {
    category: "타운하우스",
    name: "제주 브라운트리 메종타운하우스",
    address: "제주도 서귀포시 토평동 2021-1, 2번지",
    scale: "지하 1층 ~ 지상 3층, 9개동",
    year: "2017년",
    contractor: "브라운트리",
    residential: true,
  },
  {
    category: "타운하우스",
    name: "제주도 청목더웰 중문 테라스",
    address: "제주도 서귀포시 중문동 2180외 2필지",
    scale: "지하 2층 ~ 지상 8층, 2개동",
    year: "2016년",
    contractor: "㈜이델D&C, ㈜청목E&C",
    residential: true,
  },
  {
    category: "타운하우스",
    name: "광주 오포 한양수자인 립스타운하우스",
    address: "경기도 광주시 오포읍 신현리 168-2번지 일원",
    scale: "단독주택 104세대",
    year: "2016년",
    contractor: "㈜한양",
    residential: true,
  },
  {
    category: "타운하우스",
    name: "제주 청목더웰 노형",
    address: "제주도 제주시 노형동 3565-5외 4필지",
    scale: "지하 1층 ~ 지상 4층 (104세대)",
    year: "2016년",
    contractor: "㈜이델D&C, ㈜청목E&C",
    residential: true,
  },
  {
    category: "상업시설",
    name: "부평역 화성파크드림",
    address: "인천광역시 부평구 부평동 663-22번지 외 53필지",
    rooms: "16호실",
    scale: "지하 3층 ~ 지상 29층, 5개동",
    year: "2020년",
    contractor: "HXD화성개발",
    residential: false,
  },
  {
    category: "상업시설",
    name: "영종국제도시 화성파크드림 2차",
    address: "인천 경제자유구역 영종지구 영종하늘도시 A58BL",
    rooms: "8호실",
    scale: "지하 1층 ~ 지상 21층, 8개동",
    year: "2020년",
    contractor: "HXD화성개발",
    residential: false,
  },
  {
    category: "상업시설",
    name: "금천 리솜메디라이프",
    address: "서울특별시 금천구 시흥동 113-14",
    rooms: "49호실",
    scale: "지하 4층 ~ 지상 7층, 1개동",
    year: "2019년",
    contractor: "신흥개발",
    residential: false,
  },
  {
    category: "상업시설",
    name: "원주기업도시 EG The1 2차",
    address: "강원도 원주시 지정면 가곡리 원주기업도시 2-1BL",
    rooms: "24호실",
    scale: "지하 2층 ~ 지상 29층, 7개동",
    year: "2018년",
    contractor: "㈜라인건설",
    residential: false,
  },
  {
    category: "상업시설",
    name: "석촌호수 효성해링턴타워",
    address: "서울특별시 송파구 석촌동 24-3",
    rooms: "26호실",
    scale: "지하 5층 ~ 지상 22층, 1개동",
    year: "2018년",
    contractor: "효성건설",
    residential: false,
  },
  {
    category: "상업시설",
    name: "CJ 나인파크",
    address: "서울특별시 송파구 석촌동 24-11",
    rooms: "19호실",
    scale: "지하 5층 ~ 지상 22층, 2개동",
    year: "2018년",
    contractor: "CJ건설",
    residential: false,
  },
  {
    category: "상업시설",
    name: "동탄 테크노리움",
    address: "경기도 화성시 동탄면2택지지구 5BL",
    rooms: "근린생활시설 19실",
    scale: "지하 4층 ~ 지상 7층, 1개동",
    year: "2018년",
    contractor: "대창건설",
    residential: false,
  },
  {
    category: "상업시설",
    name: "인천 스카이타워 앨리웨이",
    address: "인천광역시 남구 도화개발구역 8-5, 8-7BL",
    rooms: "265호실",
    scale: "지하 3층 ~ 지상 4층",
    year: "2017년",
    contractor: "포스코건설",
    residential: false,
  },
  {
    category: "오피스텔",
    name: "빌리브 파비오 더 까사",
    address: "서울특별시 강남구 자곡동 653, 654번지",
    rooms: "215실",
    scale: "지하 4층 ~ 지상 10층, 1개동",
    year: "2019년",
    contractor: "신세계건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "동탄 테크노리움",
    address: "경기도 화성시 동탄면2택지지구 5BL",
    rooms: "122실",
    scale: "지하 4층 ~ 지상 7층, 1개동",
    year: "2018년",
    contractor: "대창건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "장한평 가우디 오피스텔",
    address: "서울특별시 동대문구 장안동 364-5번지",
    rooms: "99실",
    scale: "지하 2층 ~ 지상 18층, 1개동",
    year: "2019년",
    contractor: "해가온건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "힐스테이트 판교역",
    address: "경기도 성남시 판교지구중심상업용지 7-1BL",
    rooms: "584실",
    scale: "지하 8층 ~ 지상 20층, 1개동",
    year: "2018년",
    contractor: "현대엔지니어링",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "다산 헤리움 그랑비스타",
    address: "경기도 남양주시 다산진건지구 상업용지 1BL 1,2,3",
    rooms: "1차 : 572실 / 2차 : 624실 (총 1,196실)",
    scale: "지하 6층 ~ 지상 15층",
    year: "2017년",
    contractor: "힘찬건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "다산 자이 아이비플레이스",
    address: "경기도 남양주시 다산진건지구 주상복합 1BL",
    rooms: "270실",
    scale: "지하 1층 ~ 지상 28층, 1개동",
    year: "2017년",
    contractor: "GS건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "인천 도화 두손지젤",
    address: "인천광역시 도화지구 물류시설용지 1-4BL",
    rooms: "1,007실",
    scale: "지하 3층 ~ 지상 20층",
    year: "2017년",
    contractor: "두손건설",
    residential: true,
  },
  {
    category: "오피스텔",
    name: "김포 안강 럭스나인",
    address: "김포 김포한강로9로 75번길 132",
    rooms: "350실",
    scale: "지하 5층 ~ 지상 20층",
    year: "2016년",
    contractor: "안강건설",
    residential: true,
  },
  {
    category: "오피스",
    name: "현대 테라타워 가산DK",
    address: "서울특별시 금천구 가산동 459-14",
    rooms: "지식산업센터 380실, 지원 95실",
    scale: "지하 4층 ~ 지상 20층",
    year: "2020년",
    contractor: "현대엔지니어링",
    residential: false,
  },
  {
    category: "오피스",
    name: "다산 지앤지비즈타워",
    address: "남양주시 다산진건지구 B2-1BL",
    rooms: "지산 60실, 지원 12실, 근생 19실",
    scale: "지하 3층 ~ 지상 10층",
    year: "2018년",
    contractor: "지앤지스토리",
    residential: false,
  },
  {
    category: "오피스",
    name: "기흥 현대 테라타워",
    address: "경기도 용인시 기흥구 농서동 452",
    rooms: "679실",
    scale: "지하 2층 ~ 지상 10층",
    year: "2018년",
    contractor: "현대엔지니어링",
    residential: false,
  },
  {
    category: "생활숙박시설",
    name: "윈덤 강원 고성",
    address: "강원도 고성군 토성면 봉포리 258-9 외 8필지",
    units: "489실",
    scale: "지하 4층 ~ 지상 28층, 2개동",
    year: "2023년",
    contractor: "㈜신세계건설",
    residential: false,
  },
];

export default performanceList;
